// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TundraExts
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GuidTundraPackageString = "119242f7-44ba-4658-b26b-666721dabfae";
        public const string GuidOptionsPageGeneralString = "73319368-4511-4987-887c-165a58af5169";
        public const string GuidTundraPackageCmdSetString = "cf40d256-0233-4221-ab96-1e5710210a14";
        public static Guid GuidTundraPackage = new Guid(GuidTundraPackageString);
        public static Guid GuidOptionsPageGeneral = new Guid(GuidOptionsPageGeneralString);
        public static Guid GuidTundraPackageCmdSet = new Guid(GuidTundraPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TundraMenuGroup = 0x1020;
        public const int TundraMenu = 0x1021;
        public const int TundraCompileId = 0x0100;
        public const int TundraBuildSolutionId = 0x0101;
        public const int TundraRebuildSolutionId = 0x0102;
        public const int TundraCleanSolutionId = 0x0103;
    }
}
